export const MUSIC_GENRES = [
  "Rock/Alternative",
  "Pop",
  "Metal",
  "Punk",
  "Hip Hop",
  "Classical",
  "Electronic",
  "Jazz",
  "Blues",
  "Folk/Country",
  "Soul/Funk/R&B",
  "Big Band/Swing",
  "Reggae/Dub/Ska",
  "World",
  "Experimental",
  "Ambient/Instrumental",
  "Religious",
  "Soundtrack/Film/Theater",
  "Other",
];
